title: Subhashree Roy
logo: /images/Subhashree_new.PNG
description: Experienced professional with over 1.5 years of experience in providing IT solutions. Former System Engineer at INFOSYS PVT. LTD.            
show_downloads: true
theme: jekyll-theme-minimal
