title: Subhashree Roy
logo: /images/Subhashree.PNG
description: Experienced professional with over 1.5 years of experience in providing IT solutions. 
             Primary experience includes working in clothing and accessories retail domain. 
             A great team player contributed to a large team of over 40+ members. 
             Primary responsibility includes collaborating with stake holders to plan, design and develop simple solution for complex problems, data ingestion, integration and transformation, build functionality for data analytics, search and aggregation, mentor junior team members and help with onboarding and KT for new team members.
show_downloads: true
theme: jekyll-theme-minimal
